# Site settings
title:
email:
description: > # this means to ignore newlines until "baseurl:"
baseurl: "/capstone-2025-11"
url: "https://kookmin-sw.github.io"

twitter_username:
github_username:

# Build settings
markdown: kramdown
